apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: q1wi05f8h-java-quarkus
  janus-idp.io/tekton: q1wi05f8h-java-quarkus
  backstage.io/kubernetes-id: q1wi05f8h-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: q1wi05f8h-java-quarkus
resources:
- deployment.yaml
- route.yaml
- service.yaml
